### ISSUE TITLE
App does not open toast content on first launch

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/Jesse-Cox-for-Windows#2]
If the app was permanently closed, rather than suspended, the app will not reliably open toast content and instead just displays the list of latest videos. However, if the app is already opened or had only been suspended, toast content will launch as expected. Issue is most likely caused by [navigating to the MainPage](https://github.com/asyncwords/Jesse-Cox-for-Windows/blob/master/Jesse%20Cox%20for%20Windows/App.xaml.cs#L96) before checking for launch arguments.

**Comment by asyncwords** [comment]
Looks like navigating to the MainPage before checking for launch arguments is **not** the issue. So far I've been unable to reliably reproduce the problem. If the app is closed when clicking on a toast it will sometimes launch the content, sometimes it will just open the app, and sometimes it will do nothing.

**Comment by nozzlegear** [comment]
Fixed after converting app to WinJS in 03cc6d.
